# Air configuration file

root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ."
  full_bin = "tmp/main"
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
