version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: project/Dockerfile
    container_name: golang-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_healthy
    env_file:
      - ./project/.env   

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: yourid
      MINIO_ROOT_PASSWORD: yoursecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
